#FROM php:8.2-cli
FROM php:8.5-cli
#COPY ./src  
WORKDIR /src/myapp  
#CMD [ "php", "./index.php" ]  
#CMD ["php -a"]
#COPY . /usr/src/myapp
#WORKDIR /usr/src/myapp
#CMD [ "php", "./your-script.php" ]